import { useEffect, useState } from 'react'
const API = import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8000'
const call = (path, token, options = {}) => fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token && { Authorization: `Bearer ${token}` }) } })

function Dashboard({ token, onLogout }) {
  const [vehicles, setVehicles] = useState([]); const [editing, setEditing] = useState(null); const [message, setMessage] = useState('')
  const admin = JSON.parse(atob(token.split('.')[1])).role === 'admin'
  const load = async () => { const r = await call('/api/vehicles', token); if (r.ok) setVehicles(await r.json()) }
  useEffect(() => { load() }, [])
  const update = async event => { event.preventDefault(); const r = await call(`/api/vehicles/${editing.id}`, token, { method: 'PUT', body: JSON.stringify({ ...editing, price: Number(editing.price), quantity: Number(editing.quantity) }) }); const data = await r.json(); if (r.ok) { setVehicles(v => v.map(x => x.id === data.id ? data : x)); setEditing(null) } else setMessage(data.detail) }
  const restock = async v => { const amount = Number(window.prompt('Units to add', '1')); if (!amount) return; const r = await call(`/api/vehicles/${v.id}/restock`, token, { method: 'POST', body: JSON.stringify({ amount }) }); const data = await r.json(); if (r.ok) setVehicles(xs => xs.map(x => x.id === data.id ? data : x)) }
  const remove = async id => { if (!window.confirm('Delete this vehicle?')) return; const r = await call(`/api/vehicles/${id}`, token, { method: 'DELETE' }); if (r.ok) setVehicles(v => v.filter(x => x.id !== id)) }
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl justify-between p-5"><b>DRIVEFLOW</b><button onClick={onLogout}>Sign out</button></div></header><section className="mx-auto max-w-6xl p-6"><h1 className="text-3xl font-bold">Vehicle inventory</h1>{message && <p>{message}</p>}<div className="mt-8 grid gap-5 md:grid-cols-3">{vehicles.map(v => <article key={v.id} className="rounded-2xl bg-white p-6 shadow"><p className="text-blue-600">{v.category}</p><h2 className="text-xl font-bold">{v.make} {v.model}</h2><p className="mt-4 text-2xl font-bold">${v.price.toLocaleString()}</p><p>{v.quantity} in stock</p><button disabled={!v.quantity} className="mt-4 w-full rounded-xl bg-slate-900 py-3 text-white">Purchase vehicle</button>{admin && <><button aria-label="Edit vehicle" onClick={() => setEditing({ ...v })} className="mt-2 w-full rounded-xl border py-2">Edit vehicle</button><button onClick={() => restock(v)} className="mt-2 w-full rounded-xl border py-2">Restock</button><button onClick={() => remove(v.id)} className="mt-2 w-full rounded-xl border border-red-200 py-2 text-red-600">Delete vehicle</button></>}</article>)}</div></section>{editing && <div className="fixed inset-0 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={update} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-bold">Edit vehicle</h2><div className="mt-5 grid gap-3">{['make','model','category','price','quantity'].map(k => <input key={k} value={editing[k]} onChange={e => setEditing({ ...editing, [k]: e.target.value })} className="rounded-xl border p-3" />)}</div><div className="mt-6 flex gap-3"><button className="rounded-xl bg-blue-600 px-4 py-2 text-white">Save changes</button><button type="button" onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2">Cancel</button></div></form></div>}</main>
}

function AuthScreen({ onLogin }) {
  const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async event => { event.preventDefault(); setLoading(true); const r = await call(`/api/auth/${mode}`, null, { method: 'POST', body: JSON.stringify({ email, password }) }); const data = await r.json(); setLoading(false); if (!r.ok) return setMessage(data.detail || 'Unable to continue.'); if (mode === 'login') onLogin(data.access_token); else { setMessage('Account created. Please sign in.'); setMode('login') } }
  return <main className="grid min-h-screen place-items-center bg-slate-950 p-5"><div className="grid w-full max-w-4xl overflow-hidden rounded-3xl bg-white shadow-2xl md:grid-cols-2"><section className="bg-gradient-to-br from-blue-600 to-indigo-800 p-10 text-white"><p className="font-bold tracking-[.25em]">DRIVEFLOW</p><h1 className="mt-16 text-4xl font-bold">Inventory, beautifully managed.</h1><p className="mt-4 text-blue-100">Secure access to your dealership’s live vehicle inventory.</p></section><form onSubmit={submit} className="p-10"><h2 className="text-2xl font-bold">{mode === 'login' ? 'Welcome back' : 'Create an account'}</h2><div className="mt-7 grid gap-4"><input aria-label="Email address" value={email} onChange={e => setEmail(e.target.value)} required type="email" placeholder="Email address" className="rounded-xl border p-3"/><input aria-label="Password" value={password} onChange={e => setPassword(e.target.value)} required minLength="8" type="password" placeholder="Password" className="rounded-xl border p-3"/><button disabled={loading} className="rounded-xl bg-blue-600 p-3 font-semibold text-white">{loading ? 'Please wait...' : mode === 'login' ? 'Sign in' : 'Create account'}</button></div>{message && <p className="mt-4 text-sm">{message}</p>}<button type="button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')} className="mt-6 text-sm text-blue-600">{mode === 'login' ? 'New here? Create an account' : 'Already registered? Sign in'}</button></form></div></main>
}

export default function App() { const [token, setToken] = useState(() => localStorage.getItem('accessToken')); return token ? <Dashboard token={token} onLogout={() => { localStorage.clear(); setToken(null) }} /> : <AuthScreen onLogin={value => { localStorage.setItem('accessToken', value); setToken(value) }} /> }
