import { useEffect, useState } from 'react'
const API = import.meta.env.VITE_API_BASE_URL ?? 'http://127.0.0.1:8000'
const call = (path, token, options = {}) => fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token && { Authorization: `Bearer ${token}` }) } })

function Dashboard({ token, onLogout }) {
  const [vehicles, setVehicles] = useState([]); const [editing, setEditing] = useState(null); const [message, setMessage] = useState('')
  const admin = JSON.parse(atob(token.split('.')[1])).role === 'admin'
  const load = async () => { const r = await call('/api/vehicles', token); if (r.ok) setVehicles(await r.json()) }
  useEffect(() => { load() }, [])
  const update = async event => { event.preventDefault(); const r = await call(`/api/vehicles/${editing.id}`, token, { method: 'PUT', body: JSON.stringify({ ...editing, price: Number(editing.price), quantity: Number(editing.quantity) }) }); const data = await r.json(); if (r.ok) { setVehicles(v => v.map(x => x.id === data.id ? data : x)); setEditing(null) } else setMessage(data.detail) }
  const restock = async v => { const amount = Number(window.prompt('Units to add', '1')); if (!amount) return; const r = await call(`/api/vehicles/${v.id}/restock`, token, { method: 'POST', body: JSON.stringify({ amount }) }); const data = await r.json(); if (r.ok) setVehicles(xs => xs.map(x => x.id === data.id ? data : x)) }
  const remove = async id => { if (!window.confirm('Delete this vehicle?')) return; const r = await call(`/api/vehicles/${id}`, token, { method: 'DELETE' }); if (r.ok) setVehicles(v => v.filter(x => x.id !== id)) }
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="border-b bg-white"><div className="mx-auto flex max-w-6xl justify-between p-5"><b>DRIVEFLOW</b><button onClick={onLogout}>Sign out</button></div></header><section className="mx-auto max-w-6xl p-6"><h1 className="text-3xl font-bold">Vehicle inventory</h1>{message && <p>{message}</p>}<div className="mt-8 grid gap-5 md:grid-cols-3">{vehicles.map(v => <article key={v.id} className="rounded-2xl bg-white p-6 shadow"><p className="text-blue-600">{v.category}</p><h2 className="text-xl font-bold">{v.make} {v.model}</h2><p className="mt-4 text-2xl font-bold">${v.price.toLocaleString()}</p><p>{v.quantity} in stock</p><button disabled={!v.quantity} className="mt-4 w-full rounded-xl bg-slate-900 py-3 text-white">Purchase vehicle</button>{admin && <><button aria-label="Edit vehicle" onClick={() => setEditing({ ...v })} className="mt-2 w-full rounded-xl border py-2">Edit vehicle</button><button onClick={() => restock(v)} className="mt-2 w-full rounded-xl border py-2">Restock</button><button onClick={() => remove(v.id)} className="mt-2 w-full rounded-xl border border-red-200 py-2 text-red-600">Delete vehicle</button></>}</article>)}</div></section>{editing && <div className="fixed inset-0 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={update} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-bold">Edit vehicle</h2><div className="mt-5 grid gap-3">{['make','model','category','price','quantity'].map(k => <input key={k} value={editing[k]} onChange={e => setEditing({ ...editing, [k]: e.target.value })} className="rounded-xl border p-3" />)}</div><div className="mt-6 flex gap-3"><button className="rounded-xl bg-blue-600 px-4 py-2 text-white">Save changes</button><button type="button" onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2">Cancel</button></div></form></div>}</main>
}

export default function App() { const [token, setToken] = useState(() => localStorage.getItem('accessToken')); return token ? <Dashboard token={token} onLogout={() => { localStorage.clear(); setToken(null) }} /> : <main className="grid min-h-screen place-items-center bg-slate-950 text-white"><p>Sign in through the DriveFlow portal.</p></main> }
